### ISSUE TITLE
where can I download wubi1804r331

### ISSUE THREAD

**Issue by hengaini2055** [hakuna-m/wubiuefi#101]
as title

**Comment by hakuna-m** [comment]
Meanwhile, I added a release ([1804r331](https://github.com/hakuna-m/wubiuefi/releases/tag/1804r331)) with an exe file.

Github commits does not automatically build a release with an exe file. So there are always additional steps necessary. Last night, there was a delay because of my personal night rest. 

If there is no [release](https://github.com/hakuna-m/wubiuefi/releases) but a [commit](https://github.com/hakuna-m/wubiuefi/commits) is available, there is the possibility to download the source code and to build your own exe file. see e.g. [Clone or download button](https://help.github.com/articles/cloning-a-repository)

**Comment by hakuna-m** [comment]
I updated our [wiki](https://github.com/hakuna-m/wubiuefi/wiki), too. So ["Where can I download Wubiuefi ?"](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-can-i-download-wubiuefi-) can answer your question now.

**Comment by hengaini2055** [comment]
Thanks! I have downloaded the new release 1804331, and set up ubuntu 18.04 lts.
