### ISSUE TITLE
Unable to run wubi.exe

### ISSUE THREAD

**Issue by offline1993** [hakuna-m/wubiuefi#187]
Firstly I downloaded manually `ubuntu-18.04.4-desktop-amd64.iso`
but I use wubi-19.10 to install it
after all the wubi.exe quit without any prompt.
then I tried many times, it still exit without any prompt.
Please help~

there's the log :
[wubi-18.04.2-rev333.log](https://github.com/hakuna-m/wubiuefi/files/4431456/wubi-18.04.2-rev333.log)

**Comment by offline1993** [comment]
@hakuna-m

**Comment by offline1993** [comment]
It worked automatically after rebooting my PC several times

**Comment by hakuna-m** [comment]
> It worked automatically after rebooting my PC several times

Although the issue seems to be solved, here is my analysis of your issue. Maybe, it is helpful, if the error occurs again. 

> ```
> >>command=C:\WINDOWS\sysnative\bcdedit.exe /enum
> >>retval=1
> ```

Wubiuefi uses Windows command **bcdedit** to detect EFI configuration. An error occurs. The returned message contains some unreadable characters.

see below
```
nx                      OptIn

bootmenupolicy          Standard

```
Maybe, you can read the characters if you installed the matching code page for your language.

**Comment by offline1993** [comment]
Whoo yeah!
It successed after changing the codepage to 437

thanks!
