### ISSUE TITLE
Hibernation support

### ISSUE THREAD

**Issue by MP3Martin** [hakuna-m/wubiuefi#279]
Will **wubiuefi** ever support **hibernating**?

- When i **turn off** computer and i turn it on again, it shows **menu for selecting os**.
- But when i **hibernate windows** and turn the computer on, it **just boots to windows**

I have windows (main) and secondary os ubuntu

**Comment by hakuna-m** [comment]
>   * But when i **hibernate windows** and turn the computer on, it **just boots to windows**

It is the intention of Hibernate mode to provide a fast resume of a previous used os. So it is not an issue of Wubiuefi, it is a Windows feature to speed up booting to Windows.

Besides that, it is not recommanded to change the file system of a hibernated Windows with another os because you can loose data.

So it is also recommanded for Ubuntu without Wubiuefi to turn off hibernation if you use a dualboot with Windows.

**Comment by MP3Martin** [comment]
Thank you for this useful reply 😀
