### ISSUE TITLE
Windows is hibernated, refused to mount

### ISSUE THREAD

**Issue by aeroch** [hakuna-m/wubiuefi#29]
It states that mounting /dev/sda2 is not permitted.
Computer is always rebooted the usual way. Not suspended/hibernated.

What have I tried:
1. reinstall
2. run chkdsk /r and /f
3. disabled safe boot and quick boot
4. mounting /sda2 to /media/$dir

Don't know how to mount it. It says that I should try to mount it using 'ro' (read-only?) tag but I cannot write bash commands whilst in that screen. (/bin/sh not found)

**Comment by FuhQ** [comment]
![ubuntu error](https://cloud.githubusercontent.com/assets/24251621/20715661/93217d86-b658-11e6-95f1-43886e203211.jpg)

**Comment by FuhQ** [comment]
I use Windows 10(64 bit)| Amd radeon ASUS R9 280 series grapics processor (Radeon version is 16.11.5 Crimson edition) | ASRock motherboard.

**Comment by hakuna-m** [comment]
Try to use
`powercfg /h off`
or
`powercfg -h off`
as admin on Windows.  see [our wiki](https://github.com/hakuna-m/wubiuefi/wiki#fast-startup-and-hibernate) or a Windows forum e.g. [tenforums.com](http://www.tenforums.com/tutorials/2859-hibernate-enable-disable-windows-10-a.html)

**Comment by FuhQ** [comment]
Now i get other error...
![no root](https://cloud.githubusercontent.com/assets/24251621/20717970/f349c518-b65f-11e6-8816-4401b83c4687.jpg)

**Comment by FuhQ** [comment]
btw I used wubi14045r310 for my Amd radeon ASUS R9 280 series grapics processor is that correct?

**Comment by hakuna-m** [comment]
> Or should I try using the latest one?

`No root system is defined`
is a typical error message for [eMMC](https://github.com/hakuna-m/wubiuefi/wiki#emmc) or [NVMe](https://github.com/hakuna-m/wubiuefi/wiki#nvme) issues. [eMMC](https://github.com/hakuna-m/wubiuefi/wiki#emmc) issue has been fixed since [release 311](https://github.com/hakuna-m/wubiuefi/releases/tag/16041r311), [NVMe](https://github.com/hakuna-m/wubiuefi/wiki#nvme) issue has been fixed since [release 318](https://github.com/hakuna-m/wubiuefi/releases/tag/1610r318).

Currently, [release 311](https://github.com/hakuna-m/wubiuefi/releases/tag/16041r311) is for 16.04.1 and [release 318](https://github.com/hakuna-m/wubiuefi/releases/tag/1610r318) for 16.10.

But it is also possible to use it for 14.04.5: 
- Copy the downloaded iso from **c:\ubuntu\install\installation.iso** to a folder outside  of **c:\ubuntu** (**C:\ubuntu** will be deleted during uninstall of old version. So there should be nothing inside this folder which you need later).
- Download and copy the [latest wubi.exe](https://github.com/hakuna-m/wubiuefi/releases/latest) to the same folder as **installation.iso**.
- Run wubi.exe, it should select "Wubi EFI" for 64 bit version of an older Ubuntu version (see [various distros/versions](https://github.com/hakuna-m/wubiuefi/wiki#various-distrosversions) )

**Comment by FuhQ** [comment]
Okay I just fixed all my issues :) You can close this now.
