### ISSUE TITLE
upgrade from 18.04 to 20.04

### ISSUE THREAD

**Issue by med1coo** [hakuna-m/wubiuefi#340]
Hello,
I'm looking to perform a release upgrade from 18.04 to 20.04. The last time I attempted something similar was 2-3 years ago, and it ended up damaging my Ubuntu installation. Currently, I'm running Windows 10 alongside Ubuntu. I've had my current Ubuntu setup for 2 years, so I may not have the latest wubi files, and my sources.list has likely changed during that time.
How can I upgrade without breaking my Ubuntu? Should I also turn off Ubuntu Pro?

**Comment by med1coo** [comment]
Hey, I probably expressed myself incorrectly. I definitely installed Ubuntu over Windows (with the WubiUefi Installer) and also have a host system folder and Wubi files.

**Comment by hakuna-m** [comment]
Sorry, I missunderstood your question because the term "Ubuntu alongside Windows" is also used for Dual Boot in standard Ubuntu installer.

To your question: 

If you use the standard upgrade procedure of Ubuntu...

* [Upgrading Ubuntu desktop](https://ubuntu.com/tutorials/upgrading-ubuntu-desktop)
* [How to upgrade](https://ubuntu.com/server/docs/upgrade-introduction)

.... it should only upgrade the files on Wubi disks in folder /ubuntu/disks. It is like every update.

It is not necessary to upgrade or update also Wubiuefi on Windows which only runs two times. One time for install Ubuntu and one time to uninstall Ubuntu. For installation, some configurations depend on the installed Ubuntu release (e.g. ISO file), but installation was in the past. For uninstall, it does not matter, because it is a stupid deletion of the whole Ubuntu folder on Windows and some Windows entries which have never been changed from Ubuntu.

So theoretically, it should be no problem, if you ensure that you have sufficient free space (see e.g. [Live Resize](https://help.ubuntu.com/community/ResizeWubiDisk), and consider backing up the \ubuntu\disks directory (from Windows) in case there are any errors, or you prefer to revert to the old release.

Unfortunately, some upgrades especially from LTS to LTS, try to replace a lot of packages and configurations which can cause more issues than standard updates. e.g. it is not a good idea to remove package lupin-support in 22.04 if you need Grub menu entries and the boot loader for Wubi disks. see https://github.com/hakuna-m/wubiuefi/issues/337#issuecomment-1640816542

So sometimes it is better to uninstall Wubiuefi (be careful, Windows folder /ubuntu will be deleted, you need a back up!) and install a new release and then copy files from a saved Wubi disk to your new install. e.g. my saved Wubi disk is in Windows folder /ubuntu_1804. I can attach the Wubi disk for 18.04 with:
`sudo losetup -f /host/ubuntu_1804/disks/root.disk`

**Comment by med1coo** [comment]
Alright. I believe I now have a better understanding. If I'm correct, the root.disk files contain pictures, music, documents, and everything I've saved on Ubuntu (**/**), is that right?

I've also had some negative experiences with do-release-upgrade; most of the time, it causes a lot of issues that take me hours to fix. I think the second option is the best. What happens when I run losetup on a freshly installed Ubuntu? Is it similar to a harddrive that I can find under "On This Computer"? If not how do I access these files? Is the way also the same, when I install instead of 20.04, 22.04?

**Comment by med1coo** [comment]
@hakuna-m also the swap.disk contains just memory, which is not important?
