### ISSUE TITLE
Boot drops to a (initramfs) prompts/busybox

### ISSUE THREAD

**Issue by prakashdbhagat** [hakuna-m/wubiuefi#37]
Hi,

I have installed Ubuntu 16.10 using wubi1610r319.exe and was installed successfully. I used the os for almost 7 days and then on boot drops to a busybox. I installed ubuntu almost five times but the issue persists.

My Hardware and Operating System Configuration:

- Model: Dell Latitude E5470
- CPU: Core i7
- Storage: SSD 500 GB
- RAM: 16GB DDR4

Please do help. Let me know in case if you need further information.

Thanking you,
Prakash

**Comment by hakuna-m** [comment]
> Let me know in case if you need further information.

Busybox should display error messages. [e.g. here](https://github.com/hakuna-m/wubiuefi/issues/29#issuecomment-263599871) it displays "Windows is hibernated."

**Comment by hakuna-m** [comment]
If no message appears, try to leave initramfs shell with
`exit`
In most cases it displays mount errors with additional information e.g. 
`mounting /dev/sda2 on /isodevice failed`

Then try to find the affected device with
`blkid`

A helpful command for initramfs shell is also 
`reboot`
to reboot your system.

Some busybox reasons of other users in the past:   
 * Windows was hibernated
 * ubuntu folder on Windows was [compressed](https://technet.microsoft.com/en-us/library/cc976811.aspx)
 * Windows disk was converted to [Dynamic Disk](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363785(v=vs.85).aspx#dynamic_disks)
 * There was a copy of folder **ubuntu** on another Windows drive which was used instead of right folder.

**Comment by prakashdbhagat** [comment]
The issue was because of windows hibernate. I turned off hibernation and Ubuntu works as expected.

Thanking you,
Prakash
