### ISSUE TITLE
Multi partition with MBR/GPT virtual drive file?

### ISSUE THREAD

**Issue by wean-irdeh** [hakuna-m/wubiuefi#39]
Does this support multi partition with MBR/GPT virtual drive file? Like RAW, fixed vhd and vdi.

**Comment by hakuna-m** [comment]
It depends on your definition of "support". It is possible to get access to such virtual drives with Ubuntu. There is no difference if you installed Ubuntu by Wubi. e.g. for vdi see [here](http://askubuntu.com/questions/19430/mount-a-virtualbox-drive-image-vdi).

But it is not intended that Wubi installs Ubuntu on such virtual drives instead of single partition Wubi disks (e.g. root.disk)
