### ISSUE TITLE
The package grub UEFI couldnt be installed in /target/

### ISSUE THREAD

**Issue by dagohil** [hakuna-m/wubiuefi#42]
First of all let me thank for your efforts to make an UEFI install of Ubuntu on computers with a 32 bit boot loader possible.

I got from my daughter an ODYS TRENDBOOK 14 inch and I love it. However the hardware and firmware (32 bit bootloader and an 64 bit system) makes it hard to install Ubuntu ion the machine.

ISSUE No. 1
I tried the wubi 16.10, 16.04.2 wubi.exe to install it on my C-drive. Everything goes well. When rebooting as requested, the system tells me "EFI requested map not found and ESRT header not in XXX map. Then the ubuntu install process starts until grub should be installed. Then I receive the message "grub-efi-ia32couldnt be installed in /target/. Without bootloader the installed system will not start (All the messages are translated by me from German, so it is not exactly the the english wording)". When acknowledging the message I receive the next message that the installer is crashed. Now another message pops up "Loop-mounted file system already present. The selected (partition 3 of /var/lib/partman/devices/=dev=mmcblk1) already contains the following file system images: /ubuntu/disks/root.disk Pls uninstall these before trying again. After acknowledging all messages the system boots into a kind of live system. 

Issue No. 2
I also tried to use the installer of the live system to install ubuntu on my SD card. Everything went well until the requested reboot, which ended at a grub rescue prompt.

Pls advice what to do. Wubi installation would be fine to me as well as an install alongside to windows.

As I am not a native english speaker, pls advice me in the most simple way. Also I am not a computer expert.

best regards

Hilmar

**Comment by hakuna-m** [comment]
> Then I receive the message "grub-efi-ia32couldnt be installed in /target/

The Ubuntu desktop ISO does not contain the package [grub-efi-ia32](packages.ubuntu.com/grub-efi-ia32). So the installer needs a working internet connection during the Linux part of installation. 

i.e. If it is possible, try to use a wired internet connection during Linux part of installation. A wired internet connection should be automatically established.

There is also a second possibility. 

If the grub package error occurs, the main part of the Ubuntu installation has been completed. So it is already possible to boot your installed Ubuntu.

- Reboot to Windows
- Copy the attached file [wubildr-disk.cfg.txt](https://github.com/hakuna-m/wubiuefi/files/851402/wubildr-disk.cfg.txt) to folder **ubuntu/install**
- Rename it from **wubildr-disk.cfg.txt** to **wubildr-disk.cfg**
- Reboot to Ubuntu
- Install the missing grub packages if you want a grub menu
- Remove installer packages (e.g. ubiquity) if you need the free space

**Comment by dagohil** [comment]
Thanks a lot, possibility 2 worked (I am sure that possibility would also work, but I was unable to establish an internet connection). However, when downloading the attached file in windows, I couldn't change the name as .txt was displayed not as part of the name. I had to download it in Ubuntu (2nd machine) and change the name before transferring to my new laptop. Then it worked like a charm. 

Just another question, your description says that suspend works. Is this correct or is this my hardware? Another question: Would it now also possible to make the wubi install on my sd card?

Nevertheless, great job. Thanks. Very happy.

**Comment by hakuna-m** [comment]
> However, when downloading the attached file in windows, I couldn't change the name as .txt was displayed not as part of the name.

I added the file extension .txt because of limitations for attached files. But it should be no serious problem to change the file extension in Windows if you unhide extensions for known file types. see e.g. [here](http://www.thewindowsclub.com/show-file-extensions-in-windows)

> your description says that suspend works.

If hibernate (suspend to disk) is enabled on Windows, Wubiuefi disables it in UEFI mode during installation. see [here] (https://github.com/hakuna-m/wubiuefi/wiki#fast-startup-and-hibernate)

i.e. the hibernate feature is that it should be not necessary to disable hibernate manually in Windows.

BTW: [Hibernate has been disabled by default in policykit](https://bugs.launchpad.net/ubuntu/+source/policykit-desktop-privileges/+bug/812394) since Ubuntu 12.04 without Wubi, too.

> Would it now also possible to make the wubi install on my sd card?

If your UEFI firmware can't boot your SD card, probably it is necessary that the EFI partition and /boot are on a bootable device. The EFI partition is not really a problem because Wubiuefi uses the same partition as Windows. But /boot is within root.disk on your SD card...

**Comment by dagohil** [comment]
Thanks. Have a nice day.
