### ISSUE TITLE
Increase max installation size of 30GB?

### ISSUE THREAD

**Issue by apolinario** [hakuna-m/wubiuefi#56]
I would like to create a 120GB virtual hard drive for Ubuntu using _wubiuefi_, however it seems we are stuck at 30GB with the current interface.

I was able to find that in `src/wubi/frontends/win32/installation_page.py` line 114, the function `populate_size_list` seem to generate those options in the front end
```
    def populate_size_list(self):
        target_drive = self.get_drive()
        self.size_list_gb = []
        self.size_list.clear()
        for i in range(1, 31):
            #~ log.debug("%s < %s and %s > %s" % (i * 1000 + self.info.distro.max_iso_size/1024**2 + 100 , target_drive.free_space_mb, i * 1000 , self.info.distro.min_disk_space_mb))
            if self.info.skip_size_check \
            or i * 1000 >= self.info.distro.min_disk_space_mb: #use 1000 as it is more conservative
                if i * 1000 + self.info.distro.max_iso_size/1024**2 + 100 <= target_drive.free_space_mb:
                    self.size_list_gb.append(i)
                    self.size_list.add_item("%sGB" % i)
        self.select_default_size()
```
I'm not sure changing only the frontend would work, but I couldn't find size checks or this limitation in the backend. So I think that maybe changing the `for i in range(1, 31):` to something bigger could result in more installation sizes. 

However I couldn't compile this change to test it, because `make` isn't working with `Bash on Ubuntu on Windows` and I wasn't able to fix the MAKE issues, maybe Wine isn't supposed to run on Windows _kind-of-virtualizing_ Ubuntu. I have a complicated setup and can't `make` on Linux (that's why I need wubiuefi in the first place). So I'd like to know if I'm correct in my reasoning and request this feature in a future compiled version of _wubiuefi_

**Comment by hakuna-m** [comment]
Thanks for your suggestion. IMHO, you are right.

After installation you can increase the size over 30 GB size limit (see [ResizeandDuplicateWubiDisk](https://help.ubuntu.com/community/ResizeandDuplicateWubiDisk) or [ResizeWubiDisk](https://help.ubuntu.com/community/ResizeWubiDisk) ).

There is only a 4 GB file size limit for FAT32. But if you select 30 GB for FAT32, Wubi(uefi) splits the size in 3 virtual disks (root.disk, home.disk and usr.disk) and the used size is only 12 GB (=3 * 4 GB). So a new size limit doesn't affect installations on a FAT32 partition and it should be possible to increase the max size for NTFS partitions.

**Comment by hakuna-m** [comment]
I added a new version. see above.

IMHO, it makes no sense to create a list from min size (e.g. 5 GB) to max size (e.g. 1000 GB) using 1 GB steps.

So I created a version with 1 GB steps up to 32 GB and 64, 128, 256 and 512 GB. But it is possible to create other sizes with parameter --size. e.g.
`wubi1704r322.exe --size=120000`
sets a 120 GB disk size

I don't know if it makes really sense to create e.g. a 512 GB sized Wubi disk. In a lot of cases, there is no need to create such a large Wubi disk because you can use the Windows partition also outside the Wubi disk. The Windows partition is available as /host but of course, it has a Windows file system which has differences in comparsion with a Linux file system.

But if someone thinks that it is useful, I want to give the opportunity even I don't recommand such large disk sizes.

**Comment by BassemN** [comment]
@hakuna-m Can you add this feature also to Wubi for Ubuntu 16.04.2?

**Comment by hakuna-m** [comment]
@BassemN I plan to add all new features of 17.04 with 16.04.3 which is coming soon (see [ReleaseSchedule](https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule) ).

Do you need this feature earlier ?

Currently, you can use latest Wubiuefi release also for 16.04.2. If you manually download the desktop ISO for 16.04.2, desktop environment "Wubi EFI" (64 bit) or "Wubi" (32 bit) provide the option to install it.

**Comment by BassemN** [comment]
@hakuna-m Thanks for your time :)
I downloaded this version https://github.com/hakuna-m/wubiuefi/releases/tag/16042r319 but the max disk space was 30GB so how can I increase it?

**Comment by hakuna-m** [comment]
If you download the Wubi release with the new feature ( [wubi1704r322.exe](https://github.com/hakuna-m/wubiuefi/releases/download/1704r322/wubi1704r322.exe) ) and the ISO file for 16.04.2 ( [ubuntu-16.04.2-desktop-amd64.iso](http://releases.ubuntu.com/16.04.2/ubuntu-16.04.2-desktop-amd64.iso) ), you can use the [various distros/version feature](wiki#various-distrosversions).
i.e. If you copy both files in the same folder and run the wubi1704r322.exe, it pre-selects "Wubi EFI" as desktop environment instead of "Ubuntu" and you can install Ubuntu 16.04.2 with wubi1704r322.exe.

But it should be also no problem to increase Wubi disk after installation. e.g. "Live Resize" from [ResizeWubiDisk](https://help.ubuntu.com/community/ResizeWubiDisk) is an easy method.

**Comment by BassemN** [comment]
@hakuna-m  Thank you very much
