### ISSUE TITLE
Install is Hanging when Booting into Ubuntu

### ISSUE THREAD

**Issue by BattleToads** [hakuna-m/wubiuefi#57]
Trying to install Ubuntu with Wubi. It does everything in Windows fine but when I go to do the reboot and when Ubuntu tries to boot it is hanging and never booting. Just sitting there. This has happened on both ubuntu gnome and ubuntu mate.

**Comment by hakuna-m** [comment]
In general, if you see
![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-ESC.png)
you can press `ESC` and then the next menu  
![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-ESC-Menu.png)
provides an entry **Verbose mode** which you can select to get more information.

Sometimes the **Verbose mode** also solves some problems e.g. because of suppressing the splash screen. 

But to get the right workaround for your issue, it would be helpful if you provide some information about your computer.

e.g. It makes only sense to use "Intel graphics workarounds", if your computer uses Intel graphics.

Some information about your computer is within a log in Windows temp folder. The path name is `%temp%` or something like `C:\Users\YourWindowsName\AppData\Local\Temp`

The name of the log is `wubi-17.04-rev322.log` for wubi1704r322.exe or `wubi-16.04.2-rev319.log` for wubi16042r319.exe and so on.

**Comment by BattleToads** [comment]
[wubi-17.04-rev321.txt](https://github.com/hakuna-m/wubiuefi/files/1149692/wubi-17.04-rev321.txt)
[wubi-17.04-rev322.txt](https://github.com/hakuna-m/wubiuefi/files/1149694/wubi-17.04-rev322.txt)


So I have an Nvidia 960m graphics card however it also has an intel graphics card as well maybe it is defaulting to that. I'll give it a shot.

**Comment by hakuna-m** [comment]
![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-ESC-Menu.png)
For an Nvidia 960m graphics, edit the "Intel graphics workarounds" line by pressing `e`.
Replace both `i915.modeset=0` with `nouveau.modeset=0`. After that boot by pressing `F10`
see [here](https://askubuntu.com/a/760935)

Note: Wubiuefi uses that boot option twice - for the installer and for the installed system. If you don't need it for the installed system, because you installed a working driver, you can remove that option from **/etc/default/grub** (Replace `GRUB_CMDLINE_LINUX_DEFAULT="nouveau.modeset=0"` with `GRUB_CMDLINE_LINUX_DEFAULT=""`) and update grub afterwards with `sudo update-grub`.

**Comment by BattleToads** [comment]
That worked got ubuntu mate up and running thanks!
