### ISSUE TITLE
Unable to boot

### ISSUE THREAD

**Issue by ashwin-phadke** [hakuna-m/wubiuefi#62]
I had installed Ubuntu 17.04 using wubi and then later on after a month or so uninstalled it today, sine uninstalling and restarting my laptop is unable to boot into windows, i even change my boot ode to UEFI and secure mode off but still unable to boot into windows 10. Help needed as my few very important files are kept in Windows

**Comment by hakuna-m** [comment]
Did you change boot menu entries with programs like EasyUEFI/EASYBCD or bcdedit ? How did you uninstall Wubiuefi ? With uninstaller in "programs and features" ?

> i even change my boot ode to UEFI and secure mode off

Which was the previous boot mode ? Legacy/CSM ?

In general, Wubiuefi uninstaller removes the boot menu entry which was created during installation. The ID of that entry is stored in Windows registry. If Wubiuefi is installed, that menu entry boots to GRUB menu where you can boot into Windows.  If Wubiuefi is uninstalled you need a boot entry which can boot into Windows directly. Wubiuefi does not remove the Windows entry neither during install nor during uninstall. But if other programs remove or change it, it doesn't matter as long as Wubiuefi is installed. But if you uninstall Wubiuefi.....

In that case, probably you need to rebuild BCD. see e.g. [How To Rebuild the BCD in Windows](https://www.lifewire.com/how-to-rebuild-the-bcd-in-windows-2624508)

**Comment by ashwin-phadke** [comment]
i would like this as highly not recommended method to install ubuntu beyond 16.04 but not earlier versions.

**Comment by hakuna-m** [comment]
> to install ubuntu beyond 16.04 but not earlier versions.

And why ? IMHO, there is no essential difference between versions beyond 16.04 and earlier versions, especially for Windows.

I understand your disappointment about 17.04 because a Windows problem occured after uninstalling.

But we frequently install and uninstall Wubiuefi with different Ubuntu versions. There has never been an indication that versions beyond 16.04 cause Windows errors after uninstalling. Of course, a new Ubuntu version needs changes of Wubiuefi but a new Ubuntu version needs no change for Windows.

In fact, the Windows method of installing and uninstalling in UEFI mode has never been changed since creation of the first UEFI patches. There were only minor changes in the past. e.g. for #43. But the fix for #43 does not change the installation method and the reason for the fix was definitively not a new Ubuntu version. Additionally, the fix should help to avoid manual removing of Ubuntu which was more often the reason for issues in the past.

So, IMHO your recommendation does not really help other users. 

It would be more helpful if you add more information about your issue that we can fix the issue. The uninstaller of Wubiuefi also writes its activities into the log file within Windows temp folder (%temp%).

If [this](http://en.community.dell.com/support-forums/software-os/f/4997/t/20018732) is also your thread, I assume that Windows used hibernation. The spinning circles could be a Windows wallpaper which can also be shown after awaking from hibernation.  So maybe, some Windows programs had problems with hibernation.  

Wubiuefi disables hibernation during install and enables it during uninstall. This is not a new feature of Wubiuefi. Additionally, it is enabled in Windows 10 by default.  So hibernation should be no real problem for Windows 10.
