### ISSUE TITLE
Question: Cannot enroll key with mok manager

### ISSUE THREAD

**Issue by AndrewSav** [hakuna-m/wubiuefi#64]
Hello, I'm getting the access denied on the first screenshot here: 

https://github.com/hakuna-m/wubiuefi/wiki/MOKManager

However after pressing OK, all I see is the black screen with a message that suitable boot was not found on the hard drive, and when I press anykey it reboots in UEFI diagnostic menu and then boots windows when I exit that.

It's hp 850 g3

Am I out of luck? I don't see the screen where you are supposed to enroll the MOK key

**Comment by AndrewSav** [comment]
Never mind, there is a separate option in BIOS for that.

**Comment by rumkuhgel** [comment]
Hi, I have the same exact issue with like you mentioned, on my Acer Aspire V3-571G.

After pressing OK, i have a message on the top left corner saying this:
Failed to load image: Access denied
start_image() returned access denied

Then my Laptop reboots to windows, without the option to perform MOK management.

Is there anything i can do to fix this issue? There seems to be no option in the BIOS for that.

**Comment by hakuna-m** [comment]
As far as I know, a lot of Acer models have the option "Select an UEFI file as trusted for executing". see https://askubuntu.com/a/519619 . It is necessary to use that option instead of MOK Manager. 

For Wubiuefi you should select something like that:

- HDD0
- EFI
- ubuntu
- wubildr
- shimx64.efi

**Comment by hakuna-m** [comment]
@rumkuhgel

> Failed to load image: Access denied
> start_image() returned access denied

Meanwhile, we reproduced that issue on various computers. It seems to be a general issue of a new version of Mok Manager.

**Comment by rumkuhgel** [comment]
> As far as I know, a lot of Acer models have the option "Select an UEFI file as trusted for executing". see https://askubuntu.com/a/519619 . It is necessary to use that option instead of MOK Manager.

Just tried it and Ubuntu installs now, thank you.

**Comment by hakuna-m** [comment]
I reopened the issue because there is a Mok Manager bug, see [here](https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1692373). It is not a Wubiuefi bug but it affects Wubiuefi.

i.e. currently, ["Import a Mok"](https://github.com/hakuna-m/wubiuefi/wiki/MOKManager#import-a-mok) does not work for 17.04 and 16.04.3 

Of course, it should be not necessary to use Mok Manager (e.g. if you disable Secure Boot) and sometimes it is also not possible to use it (e.g. with a 32 bit UEFI). But it is intended as additional possibility.
