### ISSUE TITLE
After restart without importing signatures in MOK did continue to boot

### ISSUE THREAD

**Issue by samarjit** [hakuna-m/wubiuefi#72]
After restart without importing signatures in MOK did continue to boot. Now, how can I complete installation of ununtu since restart is no longer showing the installation screen?

**Comment by hakuna-m** [comment]
> since restart is no longer showing the installation screen?

Which screen do you mean with installation screen? 

If [MOKManager](https://github.com/hakuna-m/wubiuefi/wiki/MOKManager) does not appear, the following screen with ""Completing the Ubuntu installation" should appear:
 
![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-ESC.png)

and then [Ubiquity](https://wiki.ubuntu.com/Ubiquity) should install Ubuntu automatically with your pre-selected options:

![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-Ubuntu.png) 

If installation stucks between "Completing the Ubuntu installation" and [Ubiquity](https://wiki.ubuntu.com/Ubiquity) screen, try to set [boot options](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-)

**Comment by hakuna-m** [comment]
> After restart without importing signatures in MOK did continue to boot.

If blue screen with "Access denied" error appears, it is not possible to continue booting into Ubuntu. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#why-does-a-blue-screen-with-access-denied-error-appear-)

If you don't want to import MOK signatures, try to disable Secure Boot in your firmware settings . see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-change-uefi-firmware-settings-from-windows-)

**Comment by samarjit** [comment]
@hakuna-m I was not getting any prompt to continue ubuntu installation after I pressed "continue to boot" in MOK signature import screen without even importing anything. Right after this Laptop restarted and I was logged into windows. In windows I launched wubi1704r325.exe to see if it will allow me to continue. But since it says ubuntu is already installed. I thought of uninstalling and reinstalling again which fixed the problem. Still now during restart for launching ubuntu I need to press ESC to get ubuntu boot screen. If I do not press anything it loads windows. I am fine with this.
So you can close this issue ticket.

Is there a way to expand the partition (disk space) allocated for ubuntu without uninstalling reinstalling?

**Comment by hakuna-m** [comment]
> I was not getting any prompt to continue ubuntu installation after I pressed "continue to boot" in MOK signature import screen without even importing anything.

It is a known issue that after this screen

![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/MOK-Perform-Continue.png)

"Continue boot" does not always work as expected. Sometimes it boots into Windows, sometimes it boots into UEFI firmware, sometimes it stucks and so on. The reason is that different computers have different UEFI firmwares with different behaviors. 

But these MOK management screens are skipped by default, if there is no need to manage MOK signatures. So it should be not a recurrent issue.

> Still now during restart for launching ubuntu I need to press ESC to get ubuntu boot screen. If I do not press anything it loads windows.

IMHO, the reason is that UEFI boot menu boots into Windows by default. This is intended because Windows is often the preferred and familar operating system of Wubiuefi users.

But it is not intended that you don't get the UEFI boot menu. Wubiuefi sets a timeout for this menu but a lot of UEFI firmwares ignore that timeout.

So it is necessary to press a key to get this menu.  Sometimes, it is <kbd>ESC</kbd> but depending on your UEFI firmware there are also other keys like <kbd>F5</kbd>,<kbd>F8</kbd>,<kbd>F9</kbd>,<kbd>F10</kbd>,<kbd>F11</kbd> or <kbd>F12</kbd>

> Is there a way to expand the partition (disk space) allocated for ubuntu without uninstalling reinstalling?

- [ResizeandDuplicateWubiDisk](https://help.ubuntu.com/community/ResizeandDuplicateWubiDisk)
- [ResizeWubiDisk](https://help.ubuntu.com/community/ResizeWubiDisk) - IMHO, "Live Resize" at the bottom of the page is the easiest method to resize but it has some drawbacks (missing backup; if you forget `oflag=append` it overwrites Wubi disk; it does not work if file system is not clean)
- resize2fs.exe of [Cygwin project](https://www.cygwin.com)

**Comment by samarjit** [comment]
Thanks for the help. Actually I am very scared about bootloaders which is why I am going for wubi. Otherwise I would have gone for normal dual boot with proper disk partitioning. "What if I mess up with bootloaders and loose windows" comes to my mind all the time. Somewhat middle ground like wubi way of installing bootloader and dedicated disk partition for ubuntu would bring both performance and peace of mind.

**Comment by hakuna-m** [comment]
> "What if I mess up with bootloaders and loose windows"

IMHO, the risk is low to loose Windows by installing a bootloader. But there are some possibilities to get a GRUB shell instead of Windows or Ubuntu, especially if you uninstall Ubuntu by deleting it. But there is often a simple reason. Some parts of the GRUB bootloader are on Ubuntu partitions, some parts are on EFI partition (in UEFI mode) or MBR (in non-UEFI mode).

As far as I know, your Windows is in UEFI mode. In UEFI, it should be always possible to boot into Windows from UEFI boot menu. If we compare Windows only, standard dual boot and Wubiuefi dual boot, there is always the Windows way to boot into Windows: 

Windows only:
```
UEFI boot menu -> Windows Boot Manager -> Windows boot menu (hidden by default) -> Windows
```
Standard dual boot:
```
UEFI boot menu -> GRUB -> GRUB boot menu -> Ubuntu
                                         -> Windows Boot Manager -> Windows boot menu (hidden by default) -> Windows 
               -> Windows Boot Manager -> Windows boot menu (hidden by default) -> Windows
```
Wubiuefi dual boot:
```
UEFI boot menu -> Windows Boot Manager -> Windows boot menu (hidden by default) -> Windows
               -> GRUB -> GRUB boot menu -> Ubuntu
                                         -> Windows Boot Manager -> Windows boot menu (hidden by default) -> Windows 
```
Standard dual boot has a different boot order in UEFI boot menu but if you know the key(s) to get the UEFI boot menu, it is not really a problem to select Windows Boot Manager instead of GRUB.

So IMHO, there are more possibilties to loose Windows with disk partitioning....

**Comment by samarjit** [comment]
Thanks for taking time to explain to me.
