### ISSUE TITLE
Does wubiuefi support DiskImage?

### ISSUE THREAD

**Issue by AyanamiRei** [hakuna-m/wubiuefi#95]
It seems that original Wubi support install ubuntu directly using a diskimage file with `--dimagepath` option.

Something like:
`wubi.exe --dimagepath=.\ubuntu-12.04.4-wubi-amd64.tar.xz`

The diskimage is avalibal [here](http://old-releases.ubuntu.com/releases/12.04.1/ubuntu-12.04.4-wubi-amd64.tar.xz).
~~Or one can make such an image easily using an installed disk file.~~
Things is not as easy as I expected :(

I'm trying to debug the [code](https://github.com/hakuna-m/wubiuefi/blob/master/src/wubi/backends/common/backend.py#L80), but I can't get it into the diskimage path, the `dimage` variable is always None.

Any help will be greatly appreciated:)

**Comment by hakuna-m** [comment]
Wubiuefi imported the diskimage feature from old Wubi but it has never used it. The reason is that the last Wubi versions of the Ubuntu installer team have also no diskimages. 

The latest configuration file [isolist.ini](https://bazaar.launchpad.net/~ubuntu-installer/wubi/trunk/view/head:/data/isolist.ini) contains only download links for ISOs. In previous versions like rev 275 the [isolist.ini](https://bazaar.launchpad.net/~ubuntu-installer/wubi/trunk/view/275/data/isolist.ini) contains a diskimage configuration, too. 

As you see the diskimage configuration is for Ubuntu only because in the past the Ubuntu maintainer team created the Ubuntu diskimages only. But if the maintainer team does not provide such diskimages it is up to you to create one.

We also created diskimages for testing purpose. Currently, it is neccessary to format the diskimage with ext3 because Wubi(uefi) contains an old Cygwin version of resize.exe. Nevertheless, the creation with **debootstrap** and Wubiuefi patches is still possible. 

But meanwhile, I think that we can support more distros with a minimal ISO which creates the diskimage with **debootstrap** and patches during installation.  I suppose that the diskimage method has the drawback that only few maintainer of a distro will create diskimages for Wubiuefi.

**Comment by AyanamiRei** [comment]
Thanks for your detailed replay.

Finally I get it to work by directly replacing the line:
`dimage = self.info.distro.diskimage`
with
`dimage = bool(self.info.dimage_path)`
Then I can install a diskimage released by Ubuntu installer team using `--dimagepath` option. And it boots well.

But when I replace the new `root.disk` with my previously installed old one. the system can not boot.
I get messages like:
`error: no such device: CC9A16FXXXXXXXXX`
`error: no such partition`

I think maybe the old image can't recognize the new location(drive or so..)

But how can the official Ubuntu image achieve it? Obviously it be installed on any drive, and even set the username and password. Wubi just uncompress the tar package and extract the `root.disk` to the target drive. Is there any initialization script in this image and runing before system start?

Is there any writeups on how to make such an image?

**Comment by hakuna-m** [comment]
> But how can the official Ubuntu image achieve it?

As far as I know the Ubuntu installer team creates the wubi disk images and also other images with a general script.

IMHO, the main part of a working disk image is that you install package [lupin-support](https://packages.ubuntu.com/lupin-support) which contains **/usr/share/initramfs-tools/scripts/local-bottom/lupin_setup**.

and additional initramfs patches if needed. So if we mounted the disk image at mountpoint **/target**, we copied **data/custom-installation/patch/loop-remount** of Wubiuefi to **/target/etc/initramfs-tools/hooks/loop-remount**
```
sudo mkdir -p /target/etc/initramfs-tools/hooks
sudo cp data/custom-installation/patch/loop-remount /target/etc/initramfs-tools/hooks/loop-remount
sudo chmod +x /target/etc/initramfs-tools/hooks/loop-remount
```
Then we downloaded and installed all other packages including **lupin-support** with **debootstrap**. e.g. 

`sudo debootstrap --include=grub-pc,lupin-support,linux-signed-image-generic,ubuntu-standard,ubuntu-desktop --arch=i386 artful /target http://archive.ubuntu.com/ubuntu`

**Comment by AyanamiRei** [comment]
Ok, I finally figure it out how to make the preinstalled disk image bootable.

For short, just delete `/boot/grub/grub.cfg`

Reason:
On machine boot, the grub program will look for a `grub.cfg` config file in the order the file [wubildr.cfg](https://github.com/hakuna-m/wubiuefi/blob/master/data/wubildr.cfg) specifies, once you delete `/boot/grub/grub.cfg`, it will finally find the file [wubildr-disk.cfg](https://github.com/hakuna-m/wubiuefi/blob/master/data/wubildr-disk.cfg). This config file just map the the root.disk image, avoid hard coded disk UUIDs and other fixed stuffs. Then you can boot.
