### ISSUE TITLE
Kubuntu 18.04 latest daily with wubi 1804r330 problem again!

### ISSUE THREAD

**Issue by ilianiron** [hakuna-m/wubiuefi#97]
Today i have new test with wubi 1804r330 and kubuntu latest iso, downloaded from:
http://cdimage.ubuntu.com/daily-live/current/
 After installing and restart glitched kubuntu inscription for 15-20 sec, and then show command-line kubuntu-login and PC restarts! Wait for new wubi version!

**Comment by hakuna-m** [comment]
Has the issue changed since your previous tests ?

Kubuntu has also an old issue. Did you tried Kubuntu in "verbose mode" ? see [release notes](https://github.com/hakuna-m/wubiuefi/releases/tag/1804r330)

> (*) Note: Kubuntu needs a workaround ( #10 ).

Probably, it is only a typo and has nothing to do with your issue....
> http://cdimage.ubuntu.com/daily-live/current/

... is a download link for **Ubuntu**. Currently, Wubiuefi uses http://cdimage.ubuntu.com/kubuntu/daily-live/pending/ for **Kubuntu**.

**Comment by ilianiron** [comment]
Yes i have tried verbose mode but the same issue! 2 times try and restarts!

2018-04-18 22:47 GMT+03:00 hakuna matata <notifications@github.com>:

**Comment by ilianiron** [comment]
Do you have test Kubuntu and Budgie dear friend? If its possible all wait
for results! Best regards!

На чт, 19 апр. 2018 г., 17:19 hakuna matata <notifications@github.com>
написа:

**Comment by hakuna-m** [comment]
We tested Kubuntu. It worked with [latest daily build](http://cdimage.ubuntu.com/kubuntu/daily-live/pending). We did not need the workaround described in #10 , but Kubuntu still did not provide a progress bar during second part of installation. 

We also tested Lubuntu with [latest daily build](http://cdimage.ubuntu.com/lubuntu/daily-live/pending). It worked without problems. 

We got the same result for Ubuntu MATE with [latest daily build](http://cdimage.ubuntu.com/ubuntu-mate/daily-live/pending). There is also no problem in "normal mode".

But we didn't fix anything. As I assumed, there were typical issues of development releases which have been fixed by the maintainers.

**Comment by ilianiron** [comment]
Hello dear friend, today i have tested latest ubuntu daily iso from
24.04.2018, but my wubi download, not direct install like iso from
21.04.2018 and at the end of installation give me an error:
 Look at attached files.I will try with command --skimd5check-but the same
result. Kubuntu -the same!

​

2018-04-21 16:17 GMT+03:00 Ilian Zhelyazov <ilianiron@gmail.com>:

**Comment by hakuna-m** [comment]
> but my wubi download, not direct install like iso from 21.04.2018 and at the end of installation give me an error:

It is always an issue of Daily Builds that download links are sometimes broken. At creation time of wubi1804r330 the metalinks of **/daily-live/pending/** provided the correct metalinks and */daily-live/current/** did not provide it. So we decided to use */daily-live/pending/** download site.

But there is no warranty that daily changing metalinks are always correct.

For our tests, we download the ISOs wit **zsync** manually with a working Ubuntu.

e.g.

`zsync http://cdimage.ubuntu.com/ubuntu-kubuntu/daily-live/pending/bionic-desktop-amd64.iso.zsync -i kubuntu-18.04-desktop-amd64.iso -o kubuntu-18.04-desktop-amd64.iso

The name after -i is the name of an old existing ISO, the name after -o is the name of the new ISO. 

You can also use other distros of the Ubuntu family as old existing ISO. zsync downloads only the different parts of the ISOs. 

If the ISOs has changed since last download, you can disconnect internet connection to install old ISOs.   
`

**Comment by ilianiron** [comment]
Hello i'm not having working (k)ubuntu, only windows 10. All my attempts to installing with wubi gave an error 
[wubi-18.04-rev330.log](https://github.com/hakuna-m/wubiuefi/files/1952499/wubi-18.04-rev330.log)

**Comment by hakuna-m** [comment]
Really incredible.  The Ubuntu team has changed the kernel file name on ISO from **casper/vmlinuz.efi** to **caper/vmlinuz** few days before release. 

> ```
> 04-26 22:04 DEBUG  CommonBackend: Checking D:\ubuntu\install\bionic-desktop-amd64.iso
> 04-26 22:04 DEBUG  Distro:   checking Kubuntu ISO D:\ubuntu\install\bionic-desktop-amd64.iso
> 04-26 22:04 DEBUG  Distro:     does not contain casper\vmlinuz.efi
> 04-26 22:04 DEBUG  TaskList: ### Finished check_iso
> ```

I'll try to create a new version with new configuration file as soon as possible.

**Comment by hakuna-m** [comment]
If you can confirm that the issue disappears with final release of [Kubuntu 18.04](http://cdimage.ubuntu.com/kubuntu/releases/18.04/release) and [wubi1804r331](https://github.com/hakuna-m/wubiuefi/releases/tag/1804r331), please close the issue.

[wubi1804r331](https://github.com/hakuna-m/wubiuefi/releases/tag/1804r331) uses now the stable download links for 18.04. There should be no change until 18.04.1 will appear on [July 26th](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule).

**Comment by ilianiron** [comment]
Problem resolved!
